I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/capitulos/capitulo1.rpy", line 78, in script
    $ points_aline += 1
  File "game/capitulos/capitulo1.rpy", line 78, in <module>
    $ points_aline += 1
NameError: name 'points_aline' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/capitulos/capitulo1.rpy", line 78, in script
    $ points_aline += 1
  File "/Users/macbook/Documents/renpy-8.3.7-sdk/renpy/ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/macbook/Documents/renpy-8.3.7-sdk/renpy/python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/capitulos/capitulo1.rpy", line 78, in <module>
    $ points_aline += 1
NameError: name 'points_aline' is not defined

macOS-15.4-arm64-arm-64bit arm64
Ren'Py 8.3.7.25031702
test 1.0
Sun Apr 13 22:34:58 2025
